### ISSUE TITLE
documentation / tutorial of NodeMap features / trigger parameters

### ISSUE THREAD

**Issue by belalhmedan90** [photoneo-3d/photoneo-python-examples#6]
Hi,

Can you please tell me where I can find the documentation which explains the `NodeMap` features parameters, and camera trigger modes, etc? I see [this part](https://github.com/photoneo-3d/photoneo-python-examples/blob/main/GigE-V/harvesters/basic/connect_and_grab.py#L26-L38) but I can't find any documentation / tutorial, thanks.

**Comment by illesD** [comment]
Hi @belalhmedan90,
we do not provide any explicit documentation for GigE-V/GenICam.
You could read-out the GenICam XML data which provide sufficient information about the capabilities of the given device. 

You could also check the official **GenICam Standard Features Naming Convention (SFNC)** for detailed information.
Please, also check out our [PhoXiⓇ Control 1.13 - User Manual](https://www.photoneo.com/files/dw/dw/pxc/1.13/PhoXiControl1.13-UserManual-06-2024.pdf).

To retrieve the GenICam XML, you could use [AravisProject](https://github.com/AravisProject/aravis).
```
$ arv-tool-0.8 -a <ip-address> genicam
```
Or using [harvesters](https://github.com/genicam/harvesters), see [FAQ - I'd like to store the downloaded XML/Zip file. How can I do that?](https://github.com/genicam/harvesters/wiki/FAQ#id-like-to-store-the-downloaded-xmlzip-file-how-can-i-do-that). 
Although, newer versions seem to have some issues: https://github.com/genicam/harvesters/issues/438
